metasrht/blueprints/auth.py
from datetime import datetime
from flask import Blueprint, render_template, abort, request, redirect
from flask import url_for
from metasrht.audit import audit_log
from metasrht.auth import allow_registration, user_valid, prepare_user
from metasrht.auth import is_external_auth, set_user_password, set_user_email
from metasrht.auth.builtin import hash_password, check_password
from metasrht.auth_validation import validate_password
from metasrht.blueprints.security import metrics as security_metrics
from metasrht.blueprints.profile import change_email_GET
from metasrht.totp import totp
from metasrht.types import User, UserType
from metasrht.types import UserAuthFactor, FactorType, PGPKey
from metasrht.webhooks import UserWebhook
from prometheus_client import Counter
from srht.crypto import internal_anon
from srht.config import cfg, get_global_domain
from srht.database import db
from srht.flask import csrf_bypass, session
from srht.graphql import exec_gql, GraphQLError
from srht.oauth import current_user, login_user, logout_user
from srht.validation import Validation
from urllib.parse import urlparse

try:
    # This file is kept private to prevent spammers from reading it to
    # understand how to circumvent our spam prevention mechanisms.
    with open("/etc/abuse.py") as f:
        try:
            exec(f.read())
        except Exception as ex:
            print("Error loading abuse.py", ex)
            raise
except:
    def is_abuse(valid):
        return False

auth = Blueprint('auth', __name__)

origin = cfg("meta.sr.ht", "origin")
owner_name = cfg("sr.ht", "owner-name")
owner_email = cfg("sr.ht", "owner-email")
site_name = cfg("sr.ht", "site-name")
onboarding_redirect = cfg("meta.sr.ht::settings", "onboarding-redirect")
site_key_id = cfg("mail", "pgp-key-id", None)

metrics = type("metrics", tuple(), {
    c.describe()[0].name: c
    for c in [
        Counter("meta_registrations", "Number of new user registrations"),
        Counter("meta_confirmations", "Number of account confirmations"),
        Counter("meta_logins_failed", "Number of failed logins"),
        Counter("meta_logins_success", "Number of successful logins"),
        Counter("meta_logouts", "Number of sessions logged out"),
        Counter("meta_pw_resets", "Number of password resets completed"),
    ]
})

def validate_return_url(return_to):
    gdomain = get_global_domain("meta.sr.ht")
    parsed = urlparse(return_to)
    if parsed.netloc == "":
        return return_to
    netloc = parsed.netloc
    if netloc == gdomain:
        return return_to
    if "." in netloc:
        netloc = netloc[netloc.index("."):]
    if netloc == gdomain:
        return return_to
    return "/"

def issue_reset(user):
    exec_gql("meta.sr.ht", """
    mutation RequestPasswordReset($email: String!) {
        resetPassword(email: $email)
    }
    """, user=internal_anon, email=user.email)
    return render_template("forgot.html", done=True)

@auth.route("/")
def index():
    if current_user:
        return redirect(url_for("profile.profile_GET"))
    return render_template("index.html")

@auth.route("/register")
def register():
    if current_user:
        return redirect("/")
    if cfg("meta.sr.ht::billing", "enabled") != "yes":
        return redirect(url_for("auth.register_step2_GET"))
    return render_template("register.html", site_key=site_key_id)

@auth.route("/register", methods=["POST"])
def register_POST():
    is_open = allow_registration()

    valid = Validation(request)
    payment = valid.require("payment")
    if not valid.ok:
        abort(400)
    payment = payment == "yes"
    session["payment"] = payment

    return redirect(url_for("auth.register_step2_GET"))

@auth.route("/register/step2")
def register_step2_GET():
    payment = session.get("payment", "no")
    if current_user:
        return redirect("/")
    return render_template("register-step2.html",
            site_key=site_key_id, payment=payment)

@auth.route("/register/step2", methods=["POST"])
def register_step2_POST():
    if current_user:
        abort(400)
    is_open = allow_registration()
    payment = session.get("payment", False)

    valid = Validation(request)
    username = valid.require("username", friendly_name="Username")
    email = valid.require("email", friendly_name="Email address")
    password = valid.require("password", friendly_name="Password")
    pgpKey = valid.optional("pgpKey", default=None)
    if not pgpKey:
        pgpKey = None

    if not valid.ok:
        return render_template("register-step2.html", is_open=is_open,
                site_key=site_key_id, payment=payment, **valid.kwargs), 400

    if is_abuse(valid):
        return redirect("/registered")

    allow_plus_in_email = valid.optional("allow-plus-in-email")
    if "+" in email and allow_plus_in_email != "yes":
        return render_template("register-step2.html", is_open=is_open,
                site_key=site_key_id, payment=payment, **valid.kwargs), 400

    resp = exec_gql("meta.sr.ht", """
    mutation RegisterAccount($email: String!, $username: String!,
            $password: String!, $pgpKey: String) {
        registerAccount(email: $email, username: $username,
                password: $password, pgpKey: $pgpKey) {
            id
        }
    }
    """, valid=valid, user=internal_anon, username=username,
        email=email, password=password, pgpKey=pgpKey)
    if not valid.ok:
        return render_template("register-step2.html", is_open=is_open,
                site_key=site_key_id, payment=payment, **valid.kwargs), 400

    metrics.meta_registrations.inc()
    return redirect("/registered")

@auth.route("/registered")
def registered():
    return render_template("registered.html")

@auth.route("/confirm-account/<token>")
def confirm_account(token):
    try:
        resp = exec_gql("meta.sr.ht", """
        mutation ConfirmRegistration($token: String!) {
            user: confirmRegistration(token: $token) {
                id
            }
        }
        """, token=token, user=internal_anon)
    except GraphQLError:
        # Not a valid registration token
        # abort(404)

        # XXX TEMP: This same route used to be used for email changes. There
        # might be email changes in flight when the patch series changing the
        # route is deployed. So run this by the new email change route just in
        # case.
        #
        # TODO: Remove this code path in a week or so.
        return change_email_GET(token)

    user = User.query.get(resp["user"]["id"])
    assert user is not None
    login_user(user, set_cookie=True)

    metrics.meta_confirmations.inc()

    payment = session.pop("payment", False)
    if payment and cfg("meta.sr.ht::billing", "enabled") == "yes":
        return redirect(url_for("billing.billing_setup_GET"))
    else:
        return redirect(onboarding_redirect)

@auth.route("/login")
def login_GET():
    if current_user:
        return redirect("/")
    return_to = request.args.get('return_to')
    context = session.get("login_context")
    return render_template("login.html",
           return_to=return_to,
           login_context=context)

def get_challenge(factor):
    if factor.factor_type == FactorType.totp:
        return redirect("/login/challenge/totp")
    abort(500)

@auth.route("/login", methods=["POST"])
def login_POST():
    if current_user:
        return redirect("/")
    valid = Validation(request)

    username = valid.require("username", friendly_name="Username")
    password = valid.require("password", friendly_name="Password")
    return_to = valid.optional("return_to", "/")

    if not valid.ok:
        return render_template("login.html", **valid.kwargs), 400

    user_valid(valid, username, password)

    if not valid.ok:
        metrics.meta_logins_failed.inc()
        print(f"{datetime.utcnow()} Login attempt failed for {username}")
        return render_template("login.html",
            username=username,
            valid=valid)

    user = prepare_user(username)
    valid.expect(user.user_type != UserType.pending,
            "Your account is pending confirmation. Please check your inbox, or reach out to support if you did not receive an email.")
    valid.expect(user.user_type != UserType.suspended,
            f"Your account is suspended: {user.suspension_notice}. Contact support.")
    if not valid.ok:
        return render_template("login.html", **valid.kwargs), 400

    factors = (UserAuthFactor.query
        .filter(UserAuthFactor.user_id == user.id)).all()

    session.pop("login_context", None)
    if any(factors):
        session['extra_factors'] = [f.id for f in factors]
        session['authorized_user'] = user.id
        session['challenge_type'] = 'login'
        session['return_to'] = return_to
        return get_challenge(factors[0])

    login_user(user, set_cookie=True)
    print("session_login = True")
    session["session_login"] = True
    audit_log("logged in")
    print(f"Logged in account: {user.username} ({user.email})")
    db.session.commit()
    metrics.meta_logins_success.inc()
    return_to = validate_return_url(return_to)
    return redirect(return_to)

@auth.route("/login/challenge/totp")
def totp_challenge_GET():
    user = session.get('authorized_user')
    if not user:
        return redirect("/login")
    challenge_type = session.get('challenge_type')
    return render_template("totp-challenge.html", challenge_type=challenge_type)

@auth.route("/login/challenge/totp", methods=["POST"])
def totp_challenge_POST():
    user_id = session.get('authorized_user')
    factors = session.get('extra_factors')
    challenge_type = session.get('challenge_type')
    return_to = session.get('return_to') or '/'
    if not user_id or not factors:
        return redirect("/login")
    valid = Validation(request)

    code = valid.require("code")
    if not valid.ok:
        return render_template("totp-challenge.html",
            return_to=return_to, valid=valid)

metasrht/blueprints/keys.py
from datetime import datetime
from flask import Blueprint, render_template, request, redirect
from srht.graphql import exec_gql
from srht.oauth import current_user, loginrequired
from srht.validation import Validation

keys = Blueprint('keys', __name__)

@keys.route("/keys")
@loginrequired
def keys_GET():
    return render_template("keys.html", now=datetime.utcnow())

@keys.route("/keys/ssh-keys", methods=["POST"])
@loginrequired
def ssh_keys_POST():
    valid = Validation(request)
    resp = exec_gql("meta.sr.ht", """
    mutation CreateSSHKey($key: String!) {
        createSSHKey(key: $key) { id }
    }
    """, valid=valid, key=valid.source.get("ssh-key", ""))
    if not valid.ok:
        # The GraphQL parameter is called key, but we call it ssh-key to
        # disambiguate from PGP keys, which are configured on the same page.
        for err in valid.errors:
            if not err.field or err.field == "key":
                err.field = "ssh-key"
        return render_template("keys.html",
                now=datetime.utcnow(),
                ssh_key=valid.source.get("ssh-key", ""),
                **valid.kwargs), 400
    return redirect("/keys")

@keys.route("/keys/delete-ssh/<int:key_id>", methods=["POST"])
@loginrequired
def ssh_keys_delete(key_id):
    resp = exec_gql("meta.sr.ht", """
    mutation DeleteSSHKey($key: Int!) {
        deleteSSHKey(id: $key) { id }
    }
    """, key=key_id)
    return redirect("/keys")

@keys.route("/keys/pgp-keys", methods=["POST"])
@loginrequired
def pgp_keys_POST():
    valid = Validation(request)
    resp = exec_gql("meta.sr.ht", """
    mutation CreatePGPKey($key: String!) {
        createPGPKey(key: $key) { id }
    }
    """, valid=valid, key=valid.source.get("pgp-key", ""))
    if not valid.ok:
        # The GraphQL parameter is called key, but we call it pgp-key to
        # disambiguate from SSH keys, which are configured on the same page.
        for err in valid.errors:
            if not err.field or err.field == "key":
                err.field = "pgp-key"
        return render_template("keys.html",
                now=datetime.utcnow(),
                pgp_key=valid.source.get("pgp-key", ""),
                **valid.kwargs), 400
    return redirect("/keys")

@keys.route("/keys/delete-pgp/<int:key_id>", methods=["POST"])
@loginrequired
def pgp_keys_delete(key_id):
    # TODO: Move this logic into GQL
    if key_id == current_user.pgp_key_id:
        return render_template("keys.html",
                now=datetime.utcnow(),
                tried_to_delete_key_in_use=True), 400
    resp = exec_gql("meta.sr.ht", """
    mutation DeletePGPKey($key: Int!) {
        deletePGPKey(id: $key) { id }
    }
    """, key=key_id)
    return redirect("/keys")

metasrht/blueprints/privacy.py
from flask import Blueprint, Response, render_template, request, redirect
from metasrht.audit import audit_log
from metasrht.email import send_email
from metasrht.types import User, PGPKey
from srht.config import cfg
from srht.database import db
from srht.oauth import current_user, loginrequired
from srht.validation import Validation
from string import Template

privacy = Blueprint('privacy', __name__)

origin = cfg("meta.sr.ht", "origin")
owner_name = cfg("sr.ht", "owner-name")
owner_email = cfg("sr.ht", "owner-email")
site_key = cfg("mail", "pgp-pubkey", None)
site_key_id = cfg("mail", "pgp-key-id", None)
site_name = cfg("sr.ht", "site-name")

@privacy.route("/privacy")
@loginrequired
def privacy_GET():
    owner = {'name': cfg("sr.ht", "owner-name"),
             'email': cfg("sr.ht", "owner-email")}
    return render_template("privacy.html", pgp_key_id=site_key_id, owner=owner)

@privacy.route("/privacy/pubkey")
def privacy_pubkey_GET():
    if site_key:
        with open(site_key, "r") as f:
            pubkey = f.read()
    else:
        pubkey = ''
    return Response(pubkey, mimetype="text/plain")

@privacy.route("/privacy", methods=["POST"])
@loginrequired
def privacy_POST():
    valid = Validation(request)

    key_id = valid.require("pgp-key")
    key_id = key_id if key_id != "null" else None
    key = None

    if key_id:
        key = PGPKey.query.get(int(key_id))
        valid.expect(key and key.user_id == current_user.id, "Invalid PGP key")

    if not valid.ok:
        return redirect("/privacy")

    user = User.query.get(current_user.id)
    user.pgp_key = key
    audit_log("changed pgp key",
            "Set default PGP key to {}".format(key.fingerprint_hex if key else None))
    db.session.commit()

    return redirect("/privacy")

@privacy.route("/privacy/test-email", methods=["POST"])
@loginrequired
def privacy_testemail_POST():
    tmpl = Template("""Subject: Test email

This is a test email sent from $site_name to confirm that PGP is working as you
expect. This email is signed with this key:

$site_key

You may update your PGP settings here:

$root/privacy

-- 
$owner_name
$site_name
""")
    rendered = tmpl.substitute(**{
            'owner_name': owner_name,
            'site_name': site_name,
            'site_key': site_key_id,
            'root': origin
        })
    send_email(current_user.email, rendered)
    return redirect("/privacy")

metasrht/templates/are-you-sure.html
{% extends "meta.html" %}
{% block content %}
<div class="row">
  <section class="col-md-12">
    <h3>Are you sure?</h3>
    <p>Do you want to {{ blurb | safe }}? This cannot be undone.</p>
    <form method="POST" action="{{ action }}">
      {{csrf_token()}}
      <button type="submit" class="btn btn-danger">
        Yes, do it {{icon('caret-right')}}
      </button>
      <a
        href="{{ cancel }}"
        class="btn btn-default"
      >No, nevermind {{icon('caret-right')}}</a>
    </form>
  </section>
</div>
{% endblock %}

metasrht/templates/billing-complete.html
{% extends "meta.html" %}
{% block title %}
<title>Billing complete - {{cfg("sr.ht", "site-name")}} meta</title>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-6">
    <p>Your payment has been processed successfully. Thank you!</p>
    <a href="{{onboarding_redirect}}" class="btn btn-primary">
      Continue {{icon('caret-right')}}
    </a>
  </div>
</div>
{% endblock %}

metasrht/templates/billing.html
{% extends "meta.html" %}
{% block title %}
<title>Billing - {{cfg("sr.ht", "site-name")}} meta</title>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-12">
    {% if message %}
    <div class="alert alert-info">{{message}}</div>
    {% endif %}

    {# Non-paying users are redirected to /billing/initial #}

    {% if current_user.payment_status == PaymentStatus.free %}

    <div class="alert alert-info">
      Your account is <strong>exempt</strong> from billing. All features are
      available to you free of charge. You may choose to set up billing
      if you wish to support the site.
    </div>

    {% elif current_user.payment_status == PaymentStatus.subsidized %}

    <div class="alert alert-warning">
      Your account has been approved for financial aid. You will receive
      subsidized services until your financial aid term expires
      <strong>{{current_user.payment_due | date}}</strong>, at which point you
      are encouraged to apply again.
    </div>

    {% elif current_user.payment_status == PaymentStatus.current %}

    {% if not sub.autorenew %}

    <div class="alert alert-warning">
      Your renewal payment has been cancelled. When your term expires
      {{current_user.payment_due | date}}, you will no longer have
      access to paid features.
    </div>

    {% else %}

    <div class="alert alert-success">
      Your account is <strong>paid</strong> and up-to-date. Your next
      {% if sub.interval == PaymentInterval.monthly %}
      monthly
      {% else %}
      annual
      {% endif %}
      payment of {{"${:.2f}".format(sub.amount / 100.0)}} will be billed
      {{current_user.payment_due | date}}.
    </div>

    {% endif %}

    {% elif current_user.payment_status == PaymentStatus.delinquent %}

    <div class="alert alert-danger">
      <strong>Notice</strong>: Your payment is past due. Please check that your
      payment information is correct or your service may be impacted.
    </div>

    {% endif %}
  </div>
</div>

{% if current_user.payment_status == PaymentStatus.current and sub.active and sub.autorenew %}

<div class="row" style="margin-bottom: 1rem">
  <div class="col-md-3 offset-md-6">
    <a
      href="{{url_for("billing.billing_setup_GET")}}"
      class="btn btn-default btn-block"
    >Change your plan {{icon('caret-right')}}</a>
  </div>
  <div class="col-md-3">
    <form method="POST" action="{{url_for("billing.cancel_POST")}}">
      {{csrf_token()}}
      <button class="btn btn-danger btn-block">
        Cancel your plan {{icon('caret-right')}}
      </button>
    </form>
  </div>
</div>

{% elif current_user.payment_status == PaymentStatus.current and not sub.autorenew %}

<div class="row" style="margin-bottom: 1rem">
  <div class="col-md-3 offset-md-9">
    <a
      href="{{url_for("billing.billing_setup_GET")}}"
      class="btn btn-primary btn-block"
    >Renew your account {{icon('caret-right')}}</a>
  </div>
</div>

{% elif current_user.payment_status == PaymentStatus.delinquent %}

<p>
  You are subscribed to paid services with
  {% if sub.interval == PaymentInterval.monthly %}
  monthly
  {% else %}
  annual
  {% endif %} payments of
  ${{"{:.2f}".format(sub.amount / 100.0)}}.
  method to restore access to paid services.
</p>

<div class="row" style="margin-bottom: 1rem">
  <div class="col-md-4 offset-md-2">
    <a
      href="{{url_for("billing.billing_setup_GET")}}"
      class="btn btn-default btn-block"
    >Modify payment amount or term {{icon('caret-right')}}</a>
  </div>
  <div class="col-md-3">
    <form method="POST" action="{{url_for("billing.cancel_POST")}}">
      {{csrf_token()}}
      <button class="btn btn-outline-danger btn-block">
        Cancel your plan {{icon('caret-right')}}
      </button>
    </form>
  </div>
  <div class="col-md-3">
    <a
      href="{{url_for("billing.new_payment_GET")}}"
      class="btn btn-primary btn-block"
    >Add payment method {{icon('caret-right')}}</a>
  </div>
</div>

{% elif current_user.payment_status == PaymentStatus.free %}

<div class="row" style="margin-bottom: 1rem">
  <div class="col-md-3 offset-md-9">
    <a
      href="{{url_for("billing.billing_setup_GET")}}"
      class="btn btn-primary btn-block"
    >Set up billing {{icon('caret-right')}}</a>
  </div>
</div>

{% endif %}

<div class="row">
  <div class="col-md-6">
    {% if methods %}
    <h3>Payment methods</h3>
    <div class="event-list">
      {% for method in methods.data %}
      {% set card = method["card"] %}
      <div class="event row">
        <div class="col-md-8">
          {{card.brand}} ending in {{card.last4}}
          <br />
          <span class="text-muted">
            {% if card.address_zip %}
            Post code {{card.address_zip}}.
            {% endif %}
            Expires {{card.exp_month}}/{{card.exp_year}}.
          </span>
        </div>
        <div class="col-md-4">
          <div style="text-align: right">
            {% if method.id == customer.default_source %}
            {{icon('check', cls="text-success")}} Default
            {% else %}
            <form style="margin: 0;" method="POST"
              action="{{url_for("billing.payment_source_remove",
                method_id=method.id)}}">
              {{csrf_token()}}
              <button class="btn btn-link">
                Remove {{icon('times')}}
              </button>
            </form>
            <form method="POST"
              action="{{url_for("billing.payment_source_make_default",
                method_id=method.id)}}">
              {{csrf_token()}}
              <button class="btn btn-link">
                Make default {{icon('caret-right')}}
              </button>
            </form>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <a
      href="{{url_for("billing.new_payment_GET")}}"
      class="btn btn-primary pull-right"
    >New payment method {{icon('caret-right')}}</a>
    {% endif %}
  </div>

  {% if len(invoices) != 0 %}
  <div class="col-md-6">
    <h3>Invoices</h3>
    <div class="event-list">
      {% for invoice in invoices %}
      <div class="event invoice">
        <h4>
          <small class="text-success" style="margin-left: 0">
            {{icon('check')}}
          </small>
          ${{"{:.2f}".format(invoice.cents/100)}}
          <small>
            with {{invoice.source}}
          </small>
          <small>
            <a
              class="pull-right"
              href="{{url_for("billing.invoice_GET", invoice_id=invoice.id)}}"
            >Export as PDF</a>
          </small>
        </h4>
        <p>
          Paid {{invoice.created | date}}<br />
          Valid for service until {{invoice.validThru | date}}
          {% if invoice.comment %}
          <br />
          {{invoice.comment}}
          {% endif %}
        </p>
      </div>
      {% endfor %}
      <a href="{{url_for("billing.invoices_GET")}}" class="btn btn-default pull-right">
        View all invoices {{icon('caret-right')}}
      </a>
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

metasrht/templates/client-delete.html
{% extends "client-admin.html" %}
{% block content %}
<p>
  This will permenantely delete your OAuth client,
  <strong>{{ client.client_name }}</strong>, and revoke all OAuth tokens you
  have been issued.
</p>
<form method="POST">
  {{csrf_token()}}
  <button type="submit" class="btn btn-danger">
    Proceed and delete {{icon("caret-right")}}
  </button>
  <a href="/oauth" class="btn btn-default">Nevermind</a>
</form>
{% endblock %}

metasrht/templates/register-step2.html
{% extends "layout.html" %}
{% block title %}
<title>Register for {{cfg("sr.ht", "site-name")}}</title>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-10 offset-md-1">
    <h3>
      Register for {{cfg("sr.ht", "site-name")}}
      <small>
        or <a href="/login">log in</a>
      </small>
    </h3>
  </div>
</div>
{% if is_external_auth() %}
<p>Registration is disabled because {{cfg("sr.ht", "site-name")}} authentication
  is managed by a different service. Please contact the system administrator
  for further information.</p>
{% elif allow_registration() %}
{% if cfg("meta.sr.ht::billing", "enabled") == "yes" %}
<div class="row">
  <div class="col-md-10 offset-md-1">
    <p>
      {% if payment %}
      You are registering as a <strong>maintainer</strong>. After you complete
      your registration, you will be taken to the billing page, where you'll
      be provided information on payment options, financial aid, and so on.
      <a href="{{url_for("auth.register")}}">Register as a contributor instead {{icon('caret-right')}}</a>
      {% else %}
      You are registering as a <strong>contributor</strong>, which is free but
      will limit your access to some features. After you complete registration,
      you can convert to a maintainer account by setting up billing on your
      profile at any time.
      <a href="{{url_for("auth.register")}}">Register as a maintainer instead {{icon('caret-right')}}</a>
      {% endif %}
    </p>
  </div>
</div>
{% endif %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <form method="POST" action="{{url_for("auth.register_step2_POST")}}">
      {{csrf_token()}}
      <div class="form-group">
        <label for="username">Username</label>
        <input
           type="text"
           name="username"
           id="username"
           value="{{ username }}"
           class="form-control {{valid.cls("username")}}"
           required
           autocomplete="username"
           {% if not username %} autofocus{% endif %} />
        {{valid.summary("username")}}
      </div>
      <div class="form-group">
        <label for="email">Email address</label>
        <input
           type="email"
           name="email"
           id="email"
           value="{{ email }}"
           class="form-control {{valid.cls("email")}}"
           required
           {% if username and not email %} autofocus{% endif %} />
        {{valid.summary("email")}}
        {% if email and "+" in email %}
        <input type="hidden" name="allow-plus-in-email" value="yes" />
        <div class="alert alert-danger">
          <strong>Warning</strong>: in order to use {{cfg("sr.ht",
          "site-name")}} effectively, you must be able to both send <em>and</em>
          receive emails from this email address. To continue, submit the form
          again.
        </div>
        {% endif %}
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
           type="password"
           name="password"
           id="password"
           value="{{ password }}"
           class="form-control {{valid.cls("password")}}"
           required
           autocomplete="new-password"
	   maxlength="72"
           {% if username and email and not password %} autofocus{% endif %} />
        {{valid.summary("password")}}
      </div>
      {% if site_key %}
      <div class="form-group">
        <details
          {% if valid.cls("pgpKey") == "is-invalid" %}
          open
          {% endif %}
        >
          <summary>PGP public key (optional)</summary>
          <textarea
            class="form-control {{valid.cls("pgpKey")}}"
            id="pgpKey"
            name="pgpKey"
            style="font-family: monospace"
            rows="5"
            placeholder="-----BEGIN PGP PUBLIC KEY BLOCK-----
[...]
-----END PGP PUBLIC KEY BLOCK-----"
          >{{pgpKey or ""}}</textarea>
          <div id="gpg-command-section" class="form-text">
            <p>
              You can use the following command to export your PGP key (replace example@example.com with your email address):<br>
              <code id="gpg-command">gpg --armor --export-options export-minimal --export example@example.com</code>
            </p>
          </div>
          <small class="form-text">
            Emails sent from {{cfg("sr.ht", "site-name")}} are
            signed with our PGP key:<br />
            <a href="/privacy/pubkey">{{site_key}}</a>
            <p>
              If you add your PGP key here, we will also encrypt emails sent to
              you. You may change this in your settings later.
            </p>
            <p>
              <strong class="text-danger">Important!</strong>
              If you provide a PGP key now, you must be able to decrypt the
              confirmation email to complete the registration process.
            </p>
          </small>
          {{valid.summary("pgpKey")}}
        </details>
      </div>
      {% endif %}
      <button class="btn btn-primary pull-right" type="submit">
        Register {{icon("caret-right")}}
      </button>
      <p class="clearfix"></p>
    </form>
  </div>
</div>

<div class="row">
  <div class="col-md-8 offset-md-2">
    {{valid.summary()}}
  </div>
</div>

<div class="row">
  <div class="col-md-10 offset-md-1">
    <div class="alert alert-warning">
      <strong>Privacy notice</strong>:
      {{cfg("sr.ht", "site-name")}} collects the minimum amount of your personal
      information which is necessary to faciliate the features of our services.
      We do not collect or process any of your personal information for the
      purposes of marketing or analytics. We do not send unsolicited marketing
      emails. Your information is only shared with third-parties if it is
      necessary to facilitate our services, and you will be warned before this
      occurs and given an opportunity to prevent the transmission of your
      information.
      <a
        href="{{cfg("sr.ht", "privacy-policy", default="https://man.sr.ht/privacy.md")}}"
        rel="noopener"
        target="_blank"
      >Privacy policy {{icon('external-link-alt')}}</a>
    </div>
  </div>
</div>
{% else %}
<p>Registration is currently closed.</p>
{% endif %}
{% endblock %}